### ISSUE TITLE
Validación de rut con k en mayúscula

### ISSUE THREAD

**Issue by piremonte** [fdograph/rut-utilities#11]
Al validar un RUT con k en mayúscula da 'false'. 

Si se pudiese validar con "K" seria ideal, ya que igual es válido.

~~~
const { validateRut } = require("@fdograph/rut-utilities");

const result = validateRut("13198863-K");

console.log(result); // false
~~~

Saludos :)

**Comment by fdograph** [comment]
Hola! Gracias por el Issue

La librería funciona con mayúsculas y minúsculas, la expresión regular que valida un `string` es case insensitive.
Acabo de añadir un test unitario en el pull request y pasa sin problemas.
https://github.com/fdograph/rut-utilities/pull/12/files#diff-15d5d4766d44ca1363a3ff603ae5461841ec0b9a59c6a420b778a88d3a357ae3R28


Saludos!

**Comment by fdograph** [comment]
Me corrijo! :D
Este es un bug! 
El comportamiento esperado es que funcione sin importar que sea mayúscula o minúscula. Hay un bug en el método  `calculateRutVerifier` que solo considera minúsculas.

**Comment by fdograph** [comment]
Acabo de publicar una nueva versión con este bug solucionado.
Por favor actualizar a la versión `1.3.5`

Muchas gracias por reportar el bug! <3
