### ISSUE TITLE
formatRut validación de dígito verificador y cantidad dígitos base

### ISSUE THREAD

**Issue by ivanfretes** [fdograph/rut-utilities#4]
![Captura de pantalla de 2021-03-09 09-00-51](https://user-images.githubusercontent.com/751387/110467751-23ebef00-80b6-11eb-8922-256beef29204.png)

**Comment by fdograph** [comment]
Hola!
Gracias por el issue 🙂 

El problema no queda claro desde el pantallazo
Puedes explicar mejor el caso que tienes, el error y el comportamiento esperado, por favor?

**Comment by ivanfretes** [comment]
Al cargar un RUT, con 2 o más dígitos verificadores, igualmente lo formatea. Voy a hacer un pull request, si no es molestia? :)
Seria ideal que envie un exception en esos casos

**Comment by fdograph** [comment]
Por favor! adelante :)

**Comment by fdograph** [comment]
Hice un pequeño update y agregue el caso de uso que mencionas en un test aca
https://github.com/fdograph/rut-utilities/blob/master/src/tests/main.test.ts#L191

El caso funciona de la manera esperada según documentación, esto es que el rut invalido no se formatea.
Voy a marcar el issue como cerrado. Si este issue vuelve a aparecer sera necesario compartir un caso de uso junto a su contexto.

Saludos!
