### ISSUE TITLE
44.444.444-4

### ISSUE THREAD

**Issue by jaigm** [fdograph/rut-utilities#9]
Esté RUT la librería lo devuelve como inválido, pero tengo entendido que es un RUT válido.

```js

const { validateRut } = require('@fdograph/rut-utilities');

const result = validateRut('44444444-4');

console.log(result); // false
```

Saludos !

**Comment by fdograph** [comment]
Hola!
Tienes razón, el rut es matemáticamente válido. En esta libreria existe el concepto de RUT "sospechoso". Estos son RUTs que se conforman de el mismo número repetido. Ej: `22.222.222-2`, `3.333.333-3`, `9999999-9`. 
Los RUTs "sospechosos" son validados en base a [esta expresión regular](https://github.com/fdograph/rut-utilities/blob/master/src/main.ts#L28)

Para estos casos el método `validateRut` recibe un segundo parametro (que no está documentado) llamado `noSuspicious`, si ejecutas el método con este parametro en `false` se va a evitar la validación de RUTs "sospechosos". Dejé este parametro precisamente para este tipo de casos :)


```typescript
const { validateRut } = require('@fdograph/rut-utilities');

const result = validateRut('44444444-4', false);

console.log(result); // true
```

Puedes encontrar mas sobre este parametro en la [declaracion de `validateRut`](https://github.com/fdograph/rut-utilities/blob/master/src/main.ts#L96).

Tengo dentro de mis tareas documentar de mejor formar este comportamiento pero no he tenido el tiempo que quisiera para eso :/

Saludos!
